package ru.homebudget.finkeeper.ui

/**
 * Строковые ресурсы для KMP приложения.
 * Используется для локализации и упрощения поддержки текстовых констант.
 */
object Strings {
    // === Общие (Common) ===
    const val SAVE = "Сохранить"
    const val CANCEL = "Отмена"
    const val DELETE = "Удалить"
    const val ADD = "Добавить"
    const val EDIT = "Изменить"
    const val YES = "Да"
    const val NO = "Нет"
    const val NAME = "Название"
    const val AMOUNT = "Сумма"
    const val OTHER = "Другой"
    const val DONE = "Готово"
    const val CREATE = "Создать"
    const val CONFIRMATION = "Подтверждение"
    const val LOGOUT_BUTTON = "Выйти"
    const val LOGOUT_TITLE = "Выход"
    const val LOGOUT_CONFIRM = "Вы уверены, что хотите выйти?"
    const val LATER = "Позже"
    const val CHECK = "✓"
    const val PREV_MONTH = "◀"
    const val NEXT_MONTH = "▶"
    const val NEW_SOURCE = "Новый источник"

    // === Экран входа (Login) ===
    const val APP_TITLE = "FinKeeper24"
    const val APP_SUBTITLE = "Домашняя бухгалтерия"
    const val LOGIN_TITLE = "Вход"
    const val REGISTER_TITLE = "Регистрация"
    const val USERNAME_LABEL = "Имя пользователя"
    const val PASSWORD_LABEL = "Пароль"
    const val LOGIN_BUTTON = "Войти"
    const val REGISTER_BUTTON = "Зарегистрироваться"
    const val LOGIN_WITH_GOOGLE = "Войти через Google"
    const val LOGIN_WITH_YANDEX = "Войти с Яндекс ID"
    const val SOCIAL_LOGIN_HELPER = "Или используйте быстрый вход через Google или Яндекс."
    const val SOCIAL_LOGIN_IN_PROGRESS = "Завершите вход в открывшемся браузере, затем вернитесь в приложение."
    const val ALREADY_HAVE_ACCOUNT = "Уже есть аккаунт? Войти"
    const val NO_ACCOUNT = "Нет аккаунта? Зарегистрироваться"
    const val SERVER_SETTINGS = "⚙ Настройки сервера"
    const val SERVER_URL_LABEL = "URL сервера"
    const val SERVER_URL_PLACEHOLDER = "http://10.0.2.2:3002"
    const val USERNAME_HELPER = "Имя пользователя будет видно в приложении и обрезается по краям автоматически."
    const val USERNAME_MAX_LENGTH_HELPER = "Имя пользователя должно быть не длиннее 64 символов."
    const val PASSWORD_HELPER = "Пароль должен содержать не меньше 6 символов."
    const val REGISTER_HELPER = "При регистрации сразу создаётся новый аккаунт и активная сессия."
    const val CONNECTION_HELPER = "Если сеть нестабильна, попробуйте снова через несколько секунд."
    const val LOGIN_RECOVERY_HELPER = "Восстановление доступа работает только для пользователей с подтверждённым email."
    const val REGISTER_RECOVERY_HELPER = "После регистрации добавьте и подтвердите email в настройках, чтобы восстановление доступа было доступно."
    const val FORGOT_PASSWORD = "Забыли пароль?"
    const val PASSWORD_RECOVERY = "Восстановление пароля"
    const val PASSWORD_RECOVERY_EMAIL_LABEL = "Email для восстановления"
    const val PASSWORD_RECOVERY_REQUEST = "Подготовить восстановление"
    const val PASSWORD_RECOVERY_BACK_TO_LOGIN = "Вернуться ко входу"
    const val PASSWORD_RECOVERY_TOKEN_LABEL = "Токен восстановления"
    const val PASSWORD_RECOVERY_NEW_PASSWORD_LABEL = "Новый пароль"
    const val PASSWORD_RECOVERY_CONFIRM = "Сменить пароль"
    const val PASSWORD_RECOVERY_DEBUG = "Отладочный токен"
    const val PASSWORD_RECOVERY_OPEN_DEBUG = "Использовать отладочный токен"

    // === Экран обзора (Dashboard) ===
    const val DASHBOARD_TITLE = "Обзор"
    const val INCOMES = "Доходы"
    const val EXPENSES = "Расходы"
    const val SAVINGS = "Накопления"
    const val SAVINGS_PERCENT = "% в копилку"
    const val AVAILABLE = "Лимит на расходы"
    const val RESOURCE = "Ресурс"
    const val AVAILABLE_WITHOUT_SAVINGS = "Всего без накоплений"
    const val TOTAL_ASSETS = "Всего активов"
    const val FINANCIAL_DYNAMICS = "Динамика финансов"
    const val EXPENSE_STRUCTURE = "Структура расходов"

    // === Экран месяца (MonthView) ===
    const val MONTH_TITLE = "Месяц"
    const val EXPENSES_TAB = "Расходы"
    const val INCOMES_TAB = "Доходы"
    const val SPENDING_LIMIT = "Лимит трат"
    const val REMAINDER = "Остаток:"
    const val EXPENSES_BY_CATEGORIES = "Категории расходов"
    const val BUDGET = "Лимиты"
    const val NO_EXPENSES_THIS_MONTH = "Нет расходов за этот месяц"
    const val NO_INCOMES_THIS_MONTH = "Нет доходов за этот месяц"
    const val DELETE_INCOME = "Удалить доход"
    const val DELETE_EXPENSE = "Удалить расход"
    const val CONFIRM_DELETE = "Вы уверены, что хотите удалить этот доход?"
    const val CONFIRM_DELETE_EXPENSE = "Вы уверены, что хотите удалить этот расход?"
    const val SOURCE_NOT_FOUND = "Источник дохода \"%1\u0024s\" не найден. Создать его и добавить доход?"
    const val ADD_EXPENSE_IN_CATEGORY = "+ Добавить расход в \"%1\u0024s\""
    const val ADD_EXPENSE = "Добавить расход"
    const val ADD_INCOME = "Добавить доход"
    const val CATEGORY = "Категория"
    const val SOURCE = "Источник"
    const val COMMENT_OPTIONAL = "Комментарий (необязательно)"
    const val BUDGET_SETTINGS = "Настройка бюджета"
    const val ADD_EXPENSE_FOR_CATEGORY = "Добавить расход в \"%1\u0024s\""
    const val EDIT_EXPENSE = "Редактировать расход"

    // === Экран справочников (Categories) ===
    const val REFERENCE_BOOKS = "Справочники"
    const val CATEGORIES_TAB = "Категории расходов"
    const val INCOME_SOURCES_TAB = "Источники дохода"
    const val ADD_NEW = "+ Добавить"
    const val NO_CATEGORIES = "Нет категорий"
    const val NO_INCOME_SOURCES = "Нет источников дохода"
    const val NEW_CATEGORY = "Новая категория"
    const val NEW_INCOME_SOURCE = "Новый источник дохода"
    const val DELETE_CONFIRMATION = "Вы уверены? Элемент будет деактивирован."
    const val NEW_NAME = "Новая копилка"
    const val REORDER_MODE = "Режим сортировки"
    const val DRAG_HANDLE = "Перетащить"

    // === Фиксированные (регулярные) категории / источники ===
    const val FIXED_SECTION = "Фиксированные"
    const val FIXED_AMOUNT = "Сумма"
    const val AUTO_DAY = "День месяца"
    const val ADD_FIXED = "+ Добавить фиксированный"
    const val ADD_FIXED_INCOME = "+ Добавить фиксированный"
    const val NEW_FIXED_CATEGORY = "Новая фиксированная категория"
    const val NEW_FIXED_INCOME_SOURCE = "Новый фиксированный источник"
    const val EDIT_FIXED_CATEGORY = "Редактировать фиксированную категорию"
    const val EDIT_FIXED_INCOME_SOURCE = "Редактировать фиксированный источник"
    const val DAY_OF_MONTH_SUFFIX = " числа"
    const val NO_FIXED_CATEGORIES = "Нет фиксированных категорий"
    const val NO_FIXED_INCOME_SOURCES = "Нет фиксированных источников"
    const val FIXED_DELETE_CONFIRMATION = "Вы уверены? Фиксированный элемент будет деактивирован."

    // === Экран копилок (Savings) ===
    const val TOTAL_SAVINGS = "Всего накоплено"
    const val PIGGY_BANKS = "Копилки"
    const val NO_PIGGY_BANKS = "Нет копилок. Создайте первую!"
    const val FROM = "из"
    const val PERCENT = "%1\u0024d%%"
    const val DEPOSIT = "Пополнить"
    const val WITHDRAW = "Снять"
    const val NEW_PIGGY_BANK = "Новая копилка"
    const val TARGET_AMOUNT = "Целевая сумма"
    const val CURRENT_AMOUNT = "Текущая сумма"
    const val EDIT_PIGGY_BANK = "Редактировать копилку"
    const val DELETE_PIGGY_BANK = "Удалить копилку"
    const val DELETE_PIGGY_BANK_CONFIRM = "Вы уверены? Все данные копилки будут удалены."
    const val PIGGY_BANK_NAME = "Копилка: %1\u0024s"

    // === Экран настроек (Settings) ===
    const val SETTINGS = "Настройки"
    const val PROFILE = "Профиль"
    const val SECURITY = "Безопасность"
    const val ACCOUNT_PROTECTION = "Защита аккаунта"
    const val ACCOUNT_PROTECTED = "Аккаунт защищён"
    const val ACCOUNT_UNPROTECTED = "Аккаунт не защищён"
    const val ACCOUNT_PROTECTED_HELPER = "Подтверждённый email уже подключён. Самостоятельное восстановление доступа доступно."
    const val ACCOUNT_UNPROTECTED_HELPER = "Без подтверждённого email самостоятельное восстановление доступа недоступно."
    const val SECURITY_ONBOARDING_TITLE = "Добавьте email для восстановления доступа"
    const val SECURITY_ONBOARDING_MESSAGE = "Сейчас аккаунт не защищён: без подтверждённого email самостоятельное восстановление доступа недоступно. Подключите email в настройках, чтобы не потерять доступ к данным."
    const val SECURITY_ONBOARDING_ACTION = "Перейти в настройки"
    const val RECOVERY_EMAIL_LABEL = "Email для восстановления доступа"
    const val EMAIL_CONFIRMED_HELPER = "Этот email уже подтверждён и может использоваться для восстановления доступа."
    const val EMAIL_UNCONFIRMED_HELPER = "После сохранения email его нужно подтвердить, чтобы восстановление доступа стало доступно."
    const val CURRENT_PASSWORD = "Текущий пароль"
    const val SAVE_NAME = "Сохранить имя"
    const val SAVE_EMAIL = "Сохранить email"
    const val REMOVE_EMAIL = "Удалить email"
    const val RESEND_EMAIL_VERIFICATION = "Отправить подтверждение повторно"
    const val EMAIL_DEBUG_TITLE = "Отладочный токен"
    const val NEW_PASSWORD = "Новый пароль"
    const val CONFIRM_PASSWORD = "Подтвердите пароль"
    const val CHANGE_PASSWORD = "Сменить пароль"
    const val DATA_MANAGEMENT = "Управление данными"
    const val CREATE_BACKUP = "Создать резервную копию"
    const val RESTORE_FROM_BACKUP = "Восстановить из копии"
    const val BACKUP_HELPER = "Создайте резервную копию перед важными изменениями или перед переносом данных."
    const val RESTORE_HELPER = "Выберите резервную копию и подтвердите восстановление вручную. Текущие данные будут полностью заменены."
    const val BACKUP_LIST_LOADING = "Загружаем резервные копии..."
    const val BACKUP_LIST_EMPTY = "Резервные копии пока не найдены. Сначала создайте новую копию."
    const val BACKUP_CONFIRMATION_LABEL = "Подтверждение восстановления"
    const val BACKUP_CONFIRMATION_HELPER = "Введите %1\$s, чтобы разблокировать восстановление."
    const val BACKUP_CONFIRMATION_VALUE = "ВОССТАНОВИТЬ"
    const val BACKUP_SELECT_LABEL = "Выберите резервную копию"
    const val BACKUP_RESTORE_SELECTED_MESSAGE = "Восстановить данные из резервной копии от %1\$s?"
    const val ERROR_LOADING_BACKUPS = "Ошибка загрузки списка резервных копий."
    const val THEME = "Оформление"
    const val THEME_SYSTEM = "Как в системе"
    const val THEME_LIGHT = "Светлая"
    const val THEME_DARK = "Тёмная"
    const val THEME_DARK_NIGHT = "Тёмная ночь"
    const val THEME_CYBERPUNK = "Cyberpunk"
    const val THEME_BLUE_OCEAN = "Синий океан"
    const val UI_SCALE = "Масштаб интерфейса"
    const val UI_SCALE_HINT = "Размер всего интерфейса приложения"
    const val UI_SCALE_AUTO = "Авто (как в системе)"
    const val LOGOUT = "Выйти из аккаунта"
    const val CHANGE_NAME = "Сменить имя"
    const val CHANGE_NAME_CONFIRM = "Изменить имя пользователя на \"%1\u0024s\"?"
    const val CHANGE_PASSWORD_CONFIRM = "Вы уверены, что хотите сменить пароль? Для подтверждения будет использован текущий пароль."
    const val RESTORE_DATA = "Восстановить данные"
    const val RESTORE_DATA_CONFIRM = "Все текущие данные будут заменены данными из последней резервной копии. Продолжить?"
    const val BACKUP_RESTORE_CONFIRMATION_TITLE = "Восстановление из бэкапа"
    const val BACKUP_RESTORE_CONFIRMATION_MESSAGE = "Вы уверены? При восстановлении все текущие данные будут удалены и заменены данными резервной копии. Это действие нельзя отменить."
    const val BACKUP_RESTORE_BUTTON = "Восстановить"
    const val BACKUP_RESTORE_SUCCESS = "Бэкап успешно восстановлен"
    const val BACKUP_RESTORE_ERROR = "Ошибка восстановления бэкапа"

    // === Сообщения валидации и ошибок ===
    const val ENTER_USERNAME_AND_PASSWORD = "Введите имя пользователя и пароль"
    const val USERNAME_TOO_LONG = "Имя пользователя должно быть не длиннее 64 символов"
    const val PASSWORD_TOO_SHORT = "Пароль должен быть не короче 6 символов"
    const val PASSWORDS_DO_NOT_MATCH = "Пароли не совпадают"
    const val RECOVERY_EMAIL_REQUIRED = "Введите email для восстановления доступа"
    const val RECOVERY_TOKEN_REQUIRED = "Введите токен восстановления"
    const val OFFLINE_RETRY_LATER = "Сейчас нет сети. Повторите действие, когда соединение восстановится."
    const val INVALID_USERNAME_OR_PASSWORD = "Неверное имя пользователя или пароль"
    const val CONNECTION_ERROR = "Ошибка подключения к серверу"
    const val SOCIAL_BROWSER_OPEN_ERROR = "Не удалось открыть браузер для входа."
    const val SOCIAL_LOGIN_TIMEOUT = "Не удалось завершить вход через соцсеть. Попробуйте ещё раз."
    const val SESSION_EXPIRED = "Сессия истекла. Войдите снова, чтобы продолжить работу."
    const val LOADING_ERROR = "Ошибка загрузки данных"
    const val LOADING_ERROR_SHORT = "Ошибка загрузки"
    const val ERROR_ADDING_SOURCE = "Ошибка добавления источника"

    // === Сообщения об успехе ===
    const val USERNAME_UPDATED = "Имя пользователя успешно обновлено."
    const val PASSWORD_CHANGED = "Пароль успешно изменен."
    const val EMAIL_UPDATED = "Email успешно сохранён."
    const val EMAIL_REMOVED = "Email удалён."
    const val EMAIL_VERIFICATION_SENT = "Письмо для подтверждения email подготовлено."
    const val EMAIL_SAVE_REQUIRES_VERIFICATION = "Email сохранён. Подтвердите его, чтобы восстановление доступа стало доступно."
    const val EMAIL_SAVE_VERIFICATION_DELIVERY_FAILED = "Email сохранён, но письмо с подтверждением не удалось отправить. Проверьте почтовую конфигурацию сервера и попробуйте запросить подтверждение позже."
    const val EMAIL_VERIFICATION_DELIVERY_FAILED = "Не удалось отправить письмо для подтверждения email. Проверьте почтовую конфигурацию сервера и попробуйте позже."
    const val BACKUP_CREATED = "Резервная копия успешно создана."
    const val DATA_RESTORED = "Данные успешно восстановлены."
    const val RECOVERY_PASSWORD_CHANGED = "Пароль успешно изменён. Теперь можно войти с новым паролем."

    // === Сообщения об ошибках ===
    const val ERROR_UPDATING_NAME = "Ошибка обновления имени."
    const val ERROR_CHANGING_PASSWORD = "Ошибка смены пароля."
    const val ERROR_CREATING_BACKUP = "Ошибка создания резервной копии."
    const val ERROR_RESTORING_DATA = "Ошибка восстановления данных."

    // === Синхронизация ===
    const val SYNC_STATUS = "Синхронизация"
    const val SYNC_ONLINE = "В сети"
    const val SYNC_OFFLINE = "Офлайн"
    const val SYNC_IN_PROGRESS = "Идёт синхронизация данных"
    const val SYNC_PENDING_COUNT = "Ожидают отправки: %1\$d"
    const val SYNC_ALL_SENT = "Все изменения синхронизированы"
    const val SYNC_LAST_SUCCESS = "Последняя синхронизация: %1\$s"
    const val SYNC_LAST_SUCCESS_UNKNOWN = "Последняя синхронизация ещё не выполнялась"
    const val SYNC_ERROR_PREFIX = "Ошибка синхронизации: %1\$s"
    const val SYNC_RETRY = "Повторить синхронизацию"
    const val SYNC_DISMISS_ERROR = "Скрыть сообщение об ошибке"

    // === Навигация ===
    const val NAV_DASHBOARD = "Обзор"
    const val NAV_MONTH = "Месяц"
    const val NAV_CATEGORIES = "Категории"
    const val NAV_PIGGY_BANKS = "Копилки"
    const val NAV_SETTINGS = "Настр."
    const val NAV_EXIT = "Выход"

    // === Навигация месяца (иконки) ===
    const val PREV_MONTH_ICON = "◀"
    const val NEXT_MONTH_ICON = "▶"
    const val COLLAPSE_ICON = "▲"
    const val EXPAND_ICON = "▼"

    // === Символы действий ===
    const val EDIT_ICON = "✍︎"
    const val DELETE_ICON = "✕"
    const val CHECK_ICON = "✓"

    // === API ошибки ===
    const val HTTP_ERROR = "HTTP %1\u0024d: %2\u0024s"

    // === Категории по умолчанию ===
    const val SAVINGS_CATEGORY = "Пополнение копилки"
    const val NO_CATEGORY = "Без категории"

    // === Диалоги ===
    const val NEW_INCOME_SOURCE_DIALOG = "Новый источник дохода"
    const val SOURCE_NOT_FOUND_DIALOG = "Источник \"%1\u0024s\" не найден. Создать его?"
}
