name: Build Desktop Apps

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'jetbrains'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 8.14.3
    
    - name: Install WiX Toolset
      run: dotnet tool install --global wix --version 5.0.2
    
    - name: Build Windows MSI
      working-directory: ./mobile_app_client
      run: ./gradlew :composeApp:packageMsi
    
    - name: Build Windows EXE
      working-directory: ./mobile_app_client
      run: ./gradlew :composeApp:packageExe
    
    - name: Upload Windows EXE
      uses: actions/upload-artifact@v4
      with:
        name: FinKeeper-Windows-EXE
        path: mobile_app_client/composeApp/build/compose/binaries/main/exe/*.exe
    
    - name: Upload Windows MSI
      uses: actions/upload-artifact@v4
      with:
        name: FinKeeper-Windows-MSI
        path: mobile_app_client/composeApp/build/compose/binaries/main/msi/*.msi

  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'jetbrains'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 8.14.3
    
    - name: Build macOS App
      working-directory: ./mobile_app_client
      run: ./gradlew :composeApp:packageDistributionForCurrentOS
    
    - name: Upload macOS App
      uses: actions/upload-artifact@v4
      with:
        name: FinKeeper-macOS
        path: mobile_app_client/composeApp/build/compose/binaries/main/app/FinKeeper.app
